// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AttributesConfigController from "./attributes_config_controller"
application.register("attributes-config", AttributesConfigController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import PropertiesController from "./properties_controller"
application.register("properties", PropertiesController)

import Ui__LoadingController from "./ui/loading_controller"
application.register("ui--loading", Ui__LoadingController)

import Ui__ModalController from "./ui/modal_controller"
application.register("ui--modal", Ui__ModalController)
